# Generated by Django 4.2 on 2023-05-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_postalcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserWithAddress',
        ),
    ]
